targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql/**.graphql
              output: lib/models/graphql/api.graphql.dart
              naming_scheme: pathedWithFields
