targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql/output/api.graphql.dart
              schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/queries/**.graphql
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
              use_custom_parser: true
